name: cas:tool

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.10.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: make install
    - name: Lint code
      run: |
        #make lint
    - name: Run tests
      run: |
        #make test
    - name: Build app
      run: |
        #make build
    - name: Deploy
      run: |
        #make deploy
