name: cas:tool

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:


    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python 3.12.0
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'
          cache: 'pip'

    - name: Install dependencies
      run: make install
    - name: Lint code
      run: |
        #make lint
    - name: Run tests
      run: |
        #make test
    - name: Build app
      run: |
        #make build
    - name: Deploy
      run: |
        #make deploy
